require_relative './weapp_sdk.rb'

platform :ios, '10.0'

target 'demo' do
  basePath = './'

  use_frameworks!

  setup_weapp_sdk!


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
  end
  installer.pod_target_subprojects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          end
      end
  end
end

